### ISSUE TITLE
数据展示问题

### ISSUE THREAD

**Issue by TremblingMoeNew** [AuroraZiling/star-rail-asta#1]
1. 统计的时候每个十连都记反了，，，，
2. 五星单位耗费抽数展示里，常驻与UP五星列在一起但UP五星的计数是一轮大保底，这两个混在一起不符合直觉

**Comment by AuroraZiling** [comment]
1. 我会尽快修复
2. 那个中括号内的数字是指在第几抽抽到五星的

感谢反馈

**Comment by TremblingMoeNew** [comment]
我希儿大保底出的，然后计数那边写了个[102]希儿……



| |
zyy
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月18日 01:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AuroraZiling/star-rail-asta] 数据展示问题 (Issue #1) |

我会尽快修复
那个中括号内的数字是指在第几抽抽到五星的

感谢反馈

**Comment by TremblingMoeNew** [comment]
我希儿大保底出的，然后计数那边写了个[102]希儿……

**Comment by AuroraZiling** [comment]
比如从头算，在第80抽抽到瓦尔特，在第120抽抽到希儿，然后在第130抽抽到克拉拉

那文本框内容就是：[130]克拉拉[120]希儿[80]瓦尔特

耗费抽数的显示打算作为一个enhancement在以后某个版本加上

**Comment by AuroraZiling** [comment]
功能加上力（希望别出bug [384610d](https://github.com/AuroraZiling/star-rail-asta/commit/384610d32463406f07f188414627c2dcf38f15fc)
