### ISSUE TITLE
启动 Asta.exe 后无反应

### ISSUE THREAD

**Issue by flandia** [AuroraZiling/star-rail-asta#2]
版本：0.1.3
来源：GitHub Release
Log：
```
2023-05-17 23:44:37 - INFO - [GachaReport.utils] Game Path get: None
```

**Comment by AuroraZiling** [comment]
请问一下是国际服吗

**Comment by flandia** [comment]
@AuroraZiling 
不是国际服。不过游戏安装位置不是默认的，是不是跟这个有关

**Comment by AuroraZiling** [comment]
关于`C:/Users/[Name]/AppData/LocalLow/miHoYo/崩坏：星穹铁道/output_log.txt`

这个文件内有没有类似`/Star Rail/Game/StarRail_Data/webCaches\Cache\Cache_Data\data_2`的路径

**Comment by flandia** [comment]
@AuroraZiling 
存在这个文件，但不存在你所说的路径。
无论是搜索 `Star Rail`, `StarRail` 还是 `Cache_Data` 之类的关键词都没有结果

**Comment by AuroraZiling** [comment]
再麻烦看一下同目录的`Player.log`有没有包含`Loading player data from`字段，后面有没有跟着游戏路径

比如`Loading player data from D:/Program Files/Star Rail/Game/StarRail_Data/data.unity3d`

**Comment by flandia** [comment]
@AuroraZiling 
这个有，就在第一行：
`Loading player data from D:/Program Files/Star Rail/Game/StarRail_Data/data.unity3d`
跟你发的是一模一样的

**Comment by AuroraZiling** [comment]
好的，大概是`src/modules/Core/GachaReport/gacha_report_utils.py`下
```python
GAME_LOG_PATH = os.environ["userprofile"] + '/AppData/LocalLow/miHoYo/崩坏：星穹铁道/output_log.txt'


def getDefaultGameDataPath():
    if not os.path.exists(GAME_LOG_PATH):
        log.infoWrite(f"[GachaReport.utils] Game Path not found")
        return 0, "Game Log Not found"
    with open(GAME_LOG_PATH, 'r', encoding='utf-8') as f:
        logFile = f.read()
    res = re.search("([A-Z]:/.+(StarRail_Data))", logFile)
    game_path = res.group() if res else None
    log.infoWrite(f"[GachaReport.utils] Game Path get: {game_path}")
    return game_path
```
判断失误

会在0.1.4修复，感谢反馈

**Comment by AuroraZiling** [comment]
现在release了，劳烦测试下不

**Comment by flandia** [comment]
一切正常了
