### ISSUE TITLE
启动程序无反应

### ISSUE THREAD

**Issue by mutou127** [AuroraZiling/star-rail-asta#3]
asta版本：0.1.9
服务器：官服-星穹列车-国服
查过#2提到的output_log.txt和Player.log
试过低版本0.1.7和0.1.4，asta的log都显示Game Path get: None
情况如下，还需要提供什么别的log吗

![VJUPZ4C{NQ@ HZ_5FQCRM~H](https://github.com/AuroraZiling/star-rail-asta/assets/111094658/6463b393-e0f8-4c61-bafb-f874e16abbf8)

**Comment by AuroraZiling** [comment]
感谢测试，最近星铁更新，我会尽快修复游戏路径的正则搜索

**Comment by AuroraZiling** [comment]
你好，麻烦看一下[0.2.0更新](https://sangonomiya.coding.net/api/team/sangonomiya/anonymity/artifacts/repositories/17681165/packages/8807185/versions/27564322/file/download?fileName=%5B0.2.0%5DAsta.zip)是否会出现问题

**Comment by mutou127** [comment]
现在好了，辛苦啦
