### ISSUE TITLE
增量更新卡死

### ISSUE THREAD

**Issue by meowlitlot** [AuroraZiling/star-rail-asta#4]
第一次更新不使用全量更新而是增量更新的时候
数目太多会导致执行卡死，提示显示为 正在读取第9页

**Comment by AuroraZiling** [comment]
您好，能多次重复这个过程吗。
主要是想确认是不是都在同一页。

**Comment by meowlitlot** [comment]
帮朋友提的issue，他说好像没办法稳定复现，不过他说自动删除旧日志的功能好像有点问题，不管打开还是关闭都会删除

**Comment by AuroraZiling** [comment]
好的，那我这边找时间测试下

**Comment by AuroraZiling** [comment]
emmm，目前发现卡在某一页的现象是偶然的，原因大概是访问频率过快，重试大概率就好了

然后对于自动删除旧日志的问题，这个在`0.2.1`修好了
