### ISSUE TITLE
跃迁记录展示问题[BUG]

### ISSUE THREAD

**Issue by interfacew** [AuroraZiling/star-rail-asta#5]
**描述问题**
跃迁记录中基本数据的概率显示为百分数时并未转换成百分制
查看完整分析的字点击无反应
**如何复现**

**日志文件的最后5行（有最好）**  
[Asta 2023-08-26-21-00-33.log](https://github.com/AuroraZiling/star-rail-asta/files/12445389/Asta.2023-08-26-21-00-33.log)

**截图（有最好）**
![image](https://github.com/AuroraZiling/star-rail-asta/assets/131514634/32a2301a-c695-46a1-91a1-4cffc73f8e6b)

**额外信息**

**Comment by AuroraZiling** [comment]
应该修好了
