### ISSUE TITLE
开源许可证的版权信息未修改

### ISSUE THREAD

**Issue by textGamex** [AuroraZiling/star-rail-asta#6]
在 [LICENSE 635行](https://github.com/AuroraZiling/star-rail-asta/blob/main/LICENSE#L635) 和 [LICENSE 655行](https://github.com/AuroraZiling/star-rail-asta/blob/main/LICENSE#L655), 版权信息仍然是原始的.

可以参考这篇 [文章](https://blog.csdn.net/CatherineJChen/article/details/103989422)

**Comment by AuroraZiling** [comment]
感谢反馈，会近期更新

**Comment by textGamex** [comment]
> 
应该的

**Comment by textGamex** [comment]
> 感谢反馈，会近期更新

应该的
